language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/skopt
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4


matrix:
  include:
    # Linux environment to test scikit-learn against numpy and scipy master
    # installed from their CI wheels in a virtualenv with the Python
    # interpreter provided by travis.
    - name: "Python 3.6 - scikit 0.20.4"
      python: "3.6"
      env: DISTRIB="conda" PYTHON_VERSION="3.6"
           NUMPY_VERSION="1.13.3" SCIPY_VERSION="0.19.1" PYAML_VERSION="16.9.0"
           SCIKIT_LEARN_VERSION="0.20.4" MATPLOTLIB_VERSION="2.0.0" COVERAGE="false"
           JOBLIB_VERSION="0.11"
    - name: "Python 3.6 - scikit 0.21.3"
      python: "3.6"
      env: DISTRIB="conda" PYTHON_VERSION="3.6"
           NUMPY_VERSION="1.14.0" SCIPY_VERSION="1.0.0" PYAML_VERSION="16.12.0"
           SCIKIT_LEARN_VERSION="0.21.3" MATPLOTLIB_VERSION="2.0.0" COVERAGE="false"
           JOBLIB_VERSION="0.11"
    - name: "Python 3.7 - scikit 0.22.1"
      python: "3.7"
      env: DISTRIB="conda" PYTHON_VERSION="3.7"
         NUMPY_VERSION="1.16.0" SCIPY_VERSION="1.2.0" PYAML_VERSION="17.8.0"
         SCIKIT_LEARN_VERSION="0.22.1" MATPLOTLIB_VERSION="*" COVERAGE="true"
         JOBLIB_VERSION="0.13"
    - name: "Python 3.8  - scikit 0.23.2"
      python: "3.8"
      env: DISTRIB="conda" PYTHON_VERSION="3.8.1" COVERAGE="false"
           NUMPY_VERSION="1.19.1" SCIPY_VERSION="1.5.2" PYAML_VERSION="20.4.0"
           SCIKIT_LEARN_VERSION="0.23.2" JOBLIB_VERSION="0.16.0"
    - name: "Python 3.7 - sdist check"
      python: "3.7"
      env: DISTRIB="conda" PYTHON_VERSION="3.7"
           NUMPY_VERSION="*" SCIPY_VERSION="*" PYAML_VERSION="*"
           SCIKIT_LEARN_VERSION="*" MATPLOTLIB_VERSION="*" COVERAGE="false"
           JOBLIB_VERSION="*" SDIST="true"


install: source build_tools/travis/install.sh
script:
  - bash build_tools/travis/test_script.sh
  - bash build_tools/travis/test_docs.sh
after_success: source build_tools/travis/after_success.sh
deploy:
  provider: pypi
  user: __token__
  # this line together with `setup.cfg` creates universal wheels as long as
  # skopt is a python only module (no compiled code)
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: scikit-optimize/scikit-optimize
    condition: "$PYTHON_VERSION = 3.6"
  skip_cleanup: true
  skip_existing: true
  password:
    secure: "fRrICfP/zNgp/wpMO/ip03P2/G3MhKYj2q7ZJLxgCt/c/AWbobzOF5L7IyCC/Z8VycqdMv1AcF/HLQRBiNQ/ZRxy7RkXk0Bc387ZmlZo3EmCWFhCxeYIJVqBqPQL+qUplbuLFMlcHsvjZh9R2R06k7zxu6cbGrgNCl59NcOcqjqWopwvG8A/nvZ6xLriaZOWv8u6vWrav+xqWSudaBpwjzB2h244rFhWlelKXBGQKw2TKYLuN9BMuklyaTojbVIy62VbL2/SMfPwl9phTAWpxHHjHYQPdk0RpgTJ9YCroSY3HM1LcD7MgIq4Rh1N8M6lcWqoRkjNBso/oLRGWh2Pbz3vt7tssGjAYfE9Xeir5yX1u5+aXzceb4JuIovAwjwvcOAfH8VoXM8nna3o3Qev4j82+XOwYdnuRfpASE1tiRCA/MYHzLvJe8YSfB5vflSKYpTOgKCw4UGp77G/hNs1nsorzCpLoezJ+ZBaehzs9ZdJ0Y5Lm3u1pPKR47DwXHvknLOcx90YN8mZu8c7c3nsC7D9B6xnE0sO1SarIXs3p4zbpfnvc7CDIR4WCvWoT3HQDurFxG6RwkVGcyDF43Wkv3DjOlmADFSOb6z3+G6vbw3p0Bkr6vNBoLuL9eIPkyjblkBEEleLlUBHQWtkBhVeoZiTXxKSHIW7RGd1fcmHWXU="
