language: python

notifications:
  email: false

cache:
  directories:
   - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.4" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"

install: source ci_scripts/install.sh

script:
  nosetests

after_success:
    - '([ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${PYTHON_VERSION}" == "3.5" ] && source ci_scripts/deploy.sh) || echo pass'
