[build-system]
# Minimum requirements for the build system to execute.
requires = [
    "setuptools",
    "wheel",
    "numpy>=1.12",
    "scipy>=0.18",
    "scikit-learn>=0.19.1",
    "pyaml>=16.9",
    "joblib>=0.11",
]